### PR TITLE
Test that id and checksum are verified in `from_ascii_armored_str`

### PR DESCRIPTION
**Pull request by yanganto**
- add test for id, checksum check

Notes:
It does not assert the error type directly, because then we will eventually need `PartialEq` from `mnemonic` and at least in additional crates that need to be modified.

### CODE REVIEW

**Comment by yanganto** [comment]
@dr-orlovsky The CI here does not work as expected, do you think we should work on this now or not touch this now?

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
What I meant is that we need a test where we modify (1) checksum and (2) id (for instance by changing one byte in them) and make sure that `FromStr` fails with a proper error.

If you can fix the CI it will be good - you can do it in the same PR

**Comment by yanganto** [comment]
We verified `from_ascii_armored_str` with a one-bit change now.
`FromStr` can not be implemented for traits, such that nothing can be verified under `FromStr`.

neither
https://github.com/UBIDECO/ascii-armor/blob/d3c4c93396e1969efa57c30ff3145e4920c26a45/src/lib.rs#L197
nor
https://github.com/UBIDECO/ascii-armor/blob/d3c4c93396e1969efa57c30ff3145e4920c26a45/src/lib.rs#L293

**Comment by dr-orlovsky** [comment]
Sorry, I meant not `FromStr` but `from_ascii_armored_str`.

What happens with CI in this PR? Can we somehow separate CI changes and tests on checksums so we can merge one even if the other one is not working?

**Comment by yanganto** [comment]
Yeh, I agree to use another PR for the CI, it seems much more than I think.

The CI has been out of maintenance for a while, you can see it did not work for the previous PR #1 and the commit two months ago(2d4b706be6f9e84b34090fcf5d2097db81cd27e1)

One obvious reason is the features unmatch now.
As you can see there is a feature config condition here
https://github.com/UBIDECO/ascii-armor/blob/d3c4c93396e1969efa57c30ff3145e4920c26a45/src/lib.rs#L22

but there is no `base64` feature at all.
https://github.com/UBIDECO/ascii-armor/blob/d3c4c93396e1969efa57c30ff3145e4920c26a45/Cargo.toml#L32

**Comment by yanganto** [comment]
The out-of-date ci jobs are disabled, so we can easily know the status of the current PR.  And it will be fixed in #3

**Pull request merged**
